blackduck:
  url: 'url'
  trust.cert: true
  api.token: ''
  #offline.mode: true
detect:
  #cleanup: false
  project.name: 'mvn'
  project.version.name: '1.0'

  #------ADDITIONAL--MAVEN--OPTIONS------------------------------------------------------------------

  #maven.build.command
  
  #By default, Detect runs the mvn (or mvnw) command with two arguments: dependency:tree and -T1. 
  #You can use this property to insert one or more additional mvn command line arguments (goals, etc.) 
  #before the dependency:tree argument. For example: suppose you are running in bash on Linux, and want to 
  #point maven to your settings file (maven_dev_settings.xml in your home directory) and assign the
  #value 'other' to property 'reason'. You could do this with: 
  #--detect.maven.build.command='--settings \${HOME}/maven_dev_settings.xml --define reason=other'. 
  #Please note that Detect will omit any thread-specifying arguments in order to ensure the accuracy of 
  #the dependency tree.

  #---------------------------------------------------------------------------------------------------

  #maven.path

  #The path to the Maven executable (mvn or mvnw). If set, Detect will use the given Maven executable 
  #instead of searching for one.

  #---------------------------------------------------------------------------------------------------


  #maven.included.scopes
  #maven.excluded.scopes

  #code.location.name: 'name'
  #blackduck.signature.scanner.snippet.matching: 'FULL_SNIPPET_MATCHING'
  #blackduck.signature.scanner.individual.file.matching: 'ALL'
  #blackduck.signature.scanner.exclusion.name.patterns: ''
  #tools: 'BINARY_SCAN' #required for binary scan
  #tools.excluded: 'DETECTOR'
  #binary.scan.file.path: '' #required for binary scan
  #blackduck.signature.scanner.upload.source.mode: true
  #blackduck.proxy.host: hostname
  #blackduck.proxy.port: port
  #docker.tar: 'docker.tar'
  #docker.passthrough.service.timeout: 240000
  #detect.docker.image: imagename
  #detector.search.exclusion: 'Director1,Directory2'
  #impact.analysis.enabled: true
  
#logging:
  #level.com.synopsys.integration: 'DEBUG'
