blackduck:
  url: 'url'
  trust.cert: true
  api.token: ''
  #offline.mode: true
detect:
  #cleanup: false
  project.name: 'mvn'
  project.version.name: '1.0'

  #------ADDITIONAL--MAVEN--OPTIONS------------------------------------------------------------------

  #maven.build.command
  
  #By default, Detect runs the mvn (or mvnw) command with two arguments: dependency:tree and -T1. 
  #You can use this property to insert one or more additional mvn command line arguments (goals, etc.) 
  #before the dependency:tree argument. For example: suppose you are running in bash on Linux, and want to 
  #point maven to your settings file (maven_dev_settings.xml in your home directory) and assign the
  #value 'other' to property 'reason'. You could do this with: 
  #--detect.maven.build.command='--settings \${HOME}/maven_dev_settings.xml --define reason=other'. 
  #Please note that Detect will omit any thread-specifying arguments in order to ensure the accuracy of 
  #the dependency tree.

  #---------------------------------------------------------------------------------------------------

  #maven.path

  #The path to the Maven executable (mvn or mvnw). If set, Detect will use the given Maven executable 
  #instead of searching for one.

  #---------------------------------------------------------------------------------------------------
  
  #maven.included.scopes

  #A comma separated list of Maven scopes. Output will be limited to dependencies within these scopes
  #(overridden by exclude).If set, Detect will include only dependencies of the given Maven scope. 
  #This property accepts filename globbing-style wildcards. This property accepts filename globbing-style 
  #wildcards. Refer to the Configuring Synopsys Detect > Property wildcard support page for more details.

  #---------------------------------------------------------------------------------------------------

  #maven.excluded.scopes

  #A comma separated list of Maven scopes. Output will be limited to dependencies outside these scopes (overrides include).
  #If set, Detect will include only dependencies outside of the given Maven scope. This property accepts 
  #filename globbing-style wildcards. Refer to the Configuring Synopsys Detect > Property wildcard support 
  #page for more details.


  #---------------------------------------------------------------------------------------------------
  
  #maven.included.modules

  #A comma-separated list of Maven modules (subprojects) to include. As Detect parses the mvn dependency:
  #tree output for dependencies, if this property is set, Detect will include only those Maven modules 
  #specified via this property that are not excluded. Leaving this unset implies 'include all'. 
  #Exclusion rules always win. This property accepts filename globbing-style wildcards. Refer to 
  #the Configuring Synopsys Detect > Property wildcard support page for more details.

  #---------------------------------------------------------------------------------------------------

  #maven.excluded.modules

  #A comma-separated list of Maven modules (subprojects) to exclude.
  #As Detect parses the mvn dependency:tree output for dependencies, Detect will skip any Maven modules 
  #specified via this property. This property accepts filename globbing-style wildcards. Refer to the 
  #Configuring Synopsys Detect > Property wildcard support page for more details.

  #------OTHER--DETECT--OPTIONS-------------------------------------------------------------------------

  #code.location.name: 'name'
  #blackduck.signature.scanner.snippet.matching: 'FULL_SNIPPET_MATCHING'
  #blackduck.signature.scanner.individual.file.matching: 'ALL'
  #blackduck.signature.scanner.exclusion.name.patterns: ''
  #tools: 'BINARY_SCAN' #required for binary scan
  #tools.excluded: 'DETECTOR'
  #binary.scan.file.path: '' #required for binary scan
  #blackduck.signature.scanner.upload.source.mode: true
  #blackduck.proxy.host: hostname
  #blackduck.proxy.port: port
  #docker.tar: 'docker.tar'
  #docker.passthrough.service.timeout: 240000
  #detect.docker.image: imagename
  #detector.search.exclusion: 'Director1,Directory2'
  #impact.analysis.enabled: true
  
#logging:
  #level.com.synopsys.integration: 'DEBUG'
